# Generated by ariadne-codegen
# Source: sds_utils/dashboard/backend/query/graphql

from typing import Any, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .input_types import AssetKeyInput, RunsFilter
from .l_0_materializations import L0Materializations
from .run_count import RunCount
from .run_details import RunDetails
from .run_details_page import RunDetailsPage
from .runs_for_ingestion import RunsForIngestion


def gql(q: str) -> str:
    return q


class DagsterGraphQLClient(AsyncBaseClient):
    async def l_0_materializations(
        self,
        asset_key: AssetKeyInput,
        limit: int,
        before_timestamp_millis: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> L0Materializations:
        query = gql("""
            query L0Materializations($assetKey: AssetKeyInput!, $limit: Int!, $beforeTimestampMillis: String) {
              assetNodeOrError(assetKey: $assetKey) {
                __typename
                ... on AssetNode {
                  assetMaterializations(
                    limit: $limit
                    beforeTimestampMillis: $beforeTimestampMillis
                  ) {
                    runId
                    timestamp
                    partition
                    assetKey {
                      path
                    }
                    metadataEntries {
                      __typename
                      label
                      ... on TextMetadataEntry {
                        text
                      }
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "assetKey": asset_key,
            "limit": limit,
            "beforeTimestampMillis": before_timestamp_millis,
        }
        response = await self.execute(
            query=query,
            operation_name="L0Materializations",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return L0Materializations.model_validate(data)

    async def run_count(
        self, filter_: Union[Optional[RunsFilter], UnsetType] = UNSET, **kwargs: Any
    ) -> RunCount:
        query = gql("""
            query RunCount($filter: RunsFilter) {
              runsOrError(filter: $filter) {
                __typename
                ... on Runs {
                  count
                }
                ... on PythonError {
                  message
                  stack
                }
              }
            }
            """)
        variables: dict[str, object] = {"filter": filter_}
        response = await self.execute(
            query=query, operation_name="RunCount", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return RunCount.model_validate(data)

    async def run_details(
        self,
        event_limit: int,
        run_ids: Union[Optional[list[str]], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> RunDetails:
        query = gql("""
            query RunDetails($runIds: [String!], $eventLimit: Int!) {
              runsOrError(filter: {runIds: $runIds}) {
                __typename
                ... on Runs {
                  results {
                    runId
                    eventConnection(limit: $eventLimit) {
                      events {
                        __typename
                        ... on ExecutionStepSkippedEvent {
                          ...LegacySkipEventDetails
                        }
                        ... on AssetMaterializationPlannedEvent {
                          ...PlannedMaterializationEventDetails
                        }
                        ... on MaterializationEvent {
                          ...MaterializationEventDetails
                        }
                        ... on ObservationEvent {
                          ...ObservationEventDetails
                        }
                        ... on LogMessageEvent {
                          ...SubmissionResponseLogEventDetails
                        }
                      }
                      cursor
                      hasMore
                    }
                  }
                }
                ... on InvalidPipelineRunsFilterError {
                  message
                }
                ... on PythonError {
                  message
                  stack
                }
              }
            }

            fragment LegacySkipEventDetails on ExecutionStepSkippedEvent {
              runId
              stepKey
              timestamp
              message
            }

            fragment MaterializationEventDetails on MaterializationEvent {
              runId
              stepKey
              timestamp
              partition
              assetKey {
                path
              }
              metadataEntries {
                __typename
                label
                ... on TextMetadataEntry {
                  text
                }
              }
            }

            fragment ObservationEventDetails on ObservationEvent {
              runId
              stepKey
              timestamp
              partition
              assetKey {
                path
              }
              metadataEntries {
                __typename
                label
                ... on TextMetadataEntry {
                  text
                }
              }
            }

            fragment PlannedMaterializationEventDetails on AssetMaterializationPlannedEvent {
              runId
              stepKey
              timestamp
              assetKey {
                path
              }
            }

            fragment SubmissionResponseLogEventDetails on LogMessageEvent {
              runId
              stepKey
              timestamp
              message
            }
            """)
        variables: dict[str, object] = {"runIds": run_ids, "eventLimit": event_limit}
        response = await self.execute(
            query=query, operation_name="RunDetails", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return RunDetails.model_validate(data)

    async def run_details_page(
        self,
        run_id: str,
        event_limit: int,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> RunDetailsPage:
        query = gql("""
            query RunDetailsPage($runId: ID!, $cursor: String, $eventLimit: Int!) {
              runOrError(runId: $runId) {
                __typename
                ... on Run {
                  eventConnection(afterCursor: $cursor, limit: $eventLimit) {
                    events {
                      __typename
                      ... on ExecutionStepSkippedEvent {
                        ...LegacySkipEventDetails
                      }
                      ... on AssetMaterializationPlannedEvent {
                        ...PlannedMaterializationEventDetails
                      }
                      ... on MaterializationEvent {
                        ...MaterializationEventDetails
                      }
                      ... on ObservationEvent {
                        ...ObservationEventDetails
                      }
                      ... on LogMessageEvent {
                        ...SubmissionResponseLogEventDetails
                      }
                    }
                    cursor
                    hasMore
                  }
                }
                ... on RunNotFoundError {
                  message
                }
                ... on PythonError {
                  message
                  stack
                }
              }
            }

            fragment LegacySkipEventDetails on ExecutionStepSkippedEvent {
              runId
              stepKey
              timestamp
              message
            }

            fragment MaterializationEventDetails on MaterializationEvent {
              runId
              stepKey
              timestamp
              partition
              assetKey {
                path
              }
              metadataEntries {
                __typename
                label
                ... on TextMetadataEntry {
                  text
                }
              }
            }

            fragment ObservationEventDetails on ObservationEvent {
              runId
              stepKey
              timestamp
              partition
              assetKey {
                path
              }
              metadataEntries {
                __typename
                label
                ... on TextMetadataEntry {
                  text
                }
              }
            }

            fragment PlannedMaterializationEventDetails on AssetMaterializationPlannedEvent {
              runId
              stepKey
              timestamp
              assetKey {
                path
              }
            }

            fragment SubmissionResponseLogEventDetails on LogMessageEvent {
              runId
              stepKey
              timestamp
              message
            }
            """)
        variables: dict[str, object] = {
            "runId": run_id,
            "cursor": cursor,
            "eventLimit": event_limit,
        }
        response = await self.execute(
            query=query, operation_name="RunDetailsPage", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return RunDetailsPage.model_validate(data)

    async def runs_for_ingestion(
        self,
        filter_: Union[Optional[RunsFilter], UnsetType] = UNSET,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        limit: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> RunsForIngestion:
        query = gql("""
            query RunsForIngestion($filter: RunsFilter, $cursor: String, $limit: Int) {
              runsOrError(filter: $filter, cursor: $cursor, limit: $limit) {
                __typename
                ... on Runs {
                  results {
                    runId
                    jobName
                    status
                    creationTime
                    updateTime
                    startTime
                    endTime
                    parentRunId
                    rootRunId
                    assetSelection {
                      path
                    }
                    tags {
                      key
                      value
                    }
                  }
                }
                ... on PythonError {
                  message
                  stack
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "filter": filter_,
            "cursor": cursor,
            "limit": limit,
        }
        response = await self.execute(
            query=query,
            operation_name="RunsForIngestion",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return RunsForIngestion.model_validate(data)
