# Generated by ariadne-codegen
# Source: sds_utils/dashboard/backend/query/graphql

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class L0Materializations(BaseModel):
    asset_node_or_error: Union[
        "L0MaterializationsAssetNodeOrErrorAssetNode",
        "L0MaterializationsAssetNodeOrErrorAssetNotFoundError",
    ] = Field(alias="assetNodeOrError", discriminator="typename__")


class L0MaterializationsAssetNodeOrErrorAssetNode(BaseModel):
    typename__: Literal["AssetNode"] = Field(alias="__typename")
    asset_materializations: list[
        "L0MaterializationsAssetNodeOrErrorAssetNodeAssetMaterializations"
    ] = Field(alias="assetMaterializations")


class L0MaterializationsAssetNodeOrErrorAssetNodeAssetMaterializations(BaseModel):
    run_id: str = Field(alias="runId")
    timestamp: str
    partition: Optional[str]
    asset_key: Optional[
        "L0MaterializationsAssetNodeOrErrorAssetNodeAssetMaterializationsAssetKey"
    ] = Field(alias="assetKey")
    metadata_entries: list[
        Annotated[
            Union[
                "L0MaterializationsAssetNodeOrErrorAssetNodeAssetMaterializationsMetadataEntriesMetadataEntry",
                "L0MaterializationsAssetNodeOrErrorAssetNodeAssetMaterializationsMetadataEntriesTextMetadataEntry",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="metadataEntries")


class L0MaterializationsAssetNodeOrErrorAssetNodeAssetMaterializationsAssetKey(
    BaseModel
):
    path: list[str]


class L0MaterializationsAssetNodeOrErrorAssetNodeAssetMaterializationsMetadataEntriesMetadataEntry(
    BaseModel
):
    typename__: Literal[
        "AssetMetadataEntry",
        "BoolMetadataEntry",
        "CodeReferencesMetadataEntry",
        "FloatMetadataEntry",
        "IntMetadataEntry",
        "JobMetadataEntry",
        "JsonMetadataEntry",
        "MarkdownMetadataEntry",
        "MetadataEntry",
        "NotebookMetadataEntry",
        "NullMetadataEntry",
        "PathMetadataEntry",
        "PipelineRunMetadataEntry",
        "PoolMetadataEntry",
        "PythonArtifactMetadataEntry",
        "TableColumnLineageMetadataEntry",
        "TableMetadataEntry",
        "TableSchemaMetadataEntry",
        "TimestampMetadataEntry",
        "UrlMetadataEntry",
    ] = Field(alias="__typename")
    label: str


class L0MaterializationsAssetNodeOrErrorAssetNodeAssetMaterializationsMetadataEntriesTextMetadataEntry(
    BaseModel
):
    typename__: Literal["TextMetadataEntry"] = Field(alias="__typename")
    label: str
    text: str


class L0MaterializationsAssetNodeOrErrorAssetNotFoundError(BaseModel):
    typename__: Literal["AssetNotFoundError"] = Field(alias="__typename")


L0Materializations.model_rebuild()
L0MaterializationsAssetNodeOrErrorAssetNode.model_rebuild()
L0MaterializationsAssetNodeOrErrorAssetNodeAssetMaterializations.model_rebuild()
